### ISSUE TITLE
Flask Endpoint for POST Request

### ISSUE THREAD

**Issue by sbshah97** [IEEE-NITK/Ride-Sharing-Bike-Project#2]
- [x] Create a simple Flask Application which can be deployed easily. Have a static page for now!
- [x] Implement Basic HTTP Authentication for users to add data regarding the number of cycles for a day. For more information, check [here](https://flask-httpauth.readthedocs.io/en/latest/)
- [ ] Create a Flask Endpoint for sending a POST request and predicting the number of cycles required on that day. Make sure to read up on how to pickle data. You have to get the trained model from the Scikit Learn and then get a predicted output for that. Check out [this link](https://towardsdatascience.com/a-flask-api-for-serving-scikit-learn-models-c8bcdaa41daa) to know more!
- [ ] API Documentation will have to be added to the Wiki. Format for that can be found [here](https://github.com/IEEE-NITK/Ride-Sharing-Bike-Project/wiki/Endpoints)

**Comment by sbshah97** [comment]
Hi, I've finished two of the points. I'll create a Module for the Base Algorithm that we are using and will make changes on it later tonight!

**Comment by sbshah97** [comment]
ANy updates here?

**Comment by anumehaagrawal** [comment]
I have read the pickle part  , I have started implementing it

**Comment by sbshah97** [comment]
Alright! Also just talk with Hrishi about the different data visualisations and the data that he'll be needing for that!
