### ISSUE TITLE
Front End + Data Visualisation

### ISSUE THREAD

**Issue by sbshah97** [IEEE-NITK/Ride-Sharing-Bike-Project#3]
- [ ] Front end task - Work with Hrishi to design a simple UI which will visualise data that we have. Data Visualization graphs can be decided accordingly. 
- [ ] Look up on Highcharts and plot three charts to start off with! 
- [ ] Look up on Materialize CSS and check the base page at templates/index.html

## To be done
- [ ] Decide what all Data Visualisations to be used! 
- [ ] Find out what all visualisations and decide theme for the same!

**Comment by Hrily** [comment]
I did some Rapid Sketches
***
 
![image](https://user-images.githubusercontent.com/13836720/37083421-7a79d5c4-2215-11e8-95a2-c031e6255bf4.png)
Feature Selection and Data Visulaization

***

@salman-bhai 
Tell me if this is fine...

My suggestion would be to use [Materialize](http://materializecss.com/) for UI and [HighCharts](https://www.highcharts.com/) for Data Graphs.

**Comment by sbshah97** [comment]
Looks Good. Adil please proceed

**Comment by Hrily** [comment]
Since we don't have location wise data, I've updated the Sketch.

**Comment by adilashique** [comment]
So are we doing the multiple graph options kinda thing?

**Comment by Hrily** [comment]
This is one part
I've to discuss about future predictions with @salman-bhai and then I'll put up those UI designs.

Meanwhile you can proceed with this :+1:

**Comment by sbshah97** [comment]
Adil please work with templates/index.html Directory! Please do try to run the Flask app while making changes!

**Comment by adilashique** [comment]
Could you please help me out with these:
1)I have played around with the graphs a bit but I still haven't quite been able to make out how to get the data required to plot the graphs.In the graphs I plotted I myself have given some random values
2)How do you put the option at the side that Hrishi has put in the design that he he has drawn

**Comment by Hrily** [comment]
> 1)I have played around with the graphs a bit but I still haven't quite been able to make out how to get the data required to plot the graphs.In the graphs I plotted I myself have given some random values

Plotting graph from loaded data - https://github.com/Hrily/SimOS/blob/master/webapp/process_scheduling.html#L123

AJAX / XHTTPRequest - https://www.w3schools.com/xml/ajax_intro.asp

***

> 2)How do you put the option at the side that Hrishi has put in the design that he he has drawn

You could use columns from Materialize for seperating the two sections. 
Also check form elements from the site for the checkboxes, radioboxes, sliders, etc.

***
